apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp

spec:
  replicas: 1

  selector:
    matchLabels:
      app: myapp

  template:
    metadata:
      labels:
        app: myapp

    spec:
      containers:
        - name: myapp
          image: ghcr.io/kravtmk/myapp-deploy-lab:93a62312fc401c33dd304f7a704a62959ec80008
          imagePullPolicy: Always

          ports:
            - containerPort: 8000
